version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "src/LiteAnalytics.WebApi/LiteAnalytics.WebApi.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "src/LiteAnalytics.WebApi/LiteAnalytics.WebApi.csproj" }}
      - run:
          name: "Run Build step"
          command: dotnet.exe publish -c Release -r ubuntu.18.04-x64
          