version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
    steps:
      - checkout
      - run:
          name: Restore packages
          command: dotnet restore
          working_directory: src
      - run:
          name: Build
          command: dotnet build
          working_directory: src
